#Requires -Version 5.1
<#
.SYNOPSIS
    Appends the mandatory AI disclaimer to a comment/description before it is posted via MCP or az CLI.
.DESCRIPTION
    Backend-agnostic building block: it never calls `az` or an MCP tool itself, only transforms text.
    The caller passes the resulting string to whichever backend is posting the comment. No parameter
    suppresses the append -- this is the one unconditional guarantee in the D-48 tiered write policy.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$Comment
)

"$Comment`n`n<sub>Generated by AI (GitHub Copilot)</sub>"
