#Requires -Version 5.1
<#
.SYNOPSIS
    Updates an existing Azure DevOps work item with a state transition and/or a comment,
    after explicit human approval (second and last allowed mutation).
.DESCRIPTION
    Precondition (outside this script, same rule as Create-AdoPullRequest.ps1): the agent
    shows the rendered Comment text (and the target State, if set) in chat and obtains an
    explicit approval before this script is called without -WhatIf. The technical
    ShouldProcess confirmation does not replace that content preview -- both are mandatory.
    Write only with human confirmation.

    Allowlist: exactly one Azure CLI command (`az boards work-item update`), plus the
    read-only `az boards work-item show` used for the preflight state check. Never creates,
    deletes, or reassigns a work item, and never changes its type/title/area/iteration path.
#>
[CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'High')]
param(
    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [string]$Organization,

    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [string]$Project,

    [Parameter(Mandatory)]
    [ValidateRange(1, [int]::MaxValue)]
    [int]$WorkItemId,

    [string]$State,

    [string]$Comment
)

if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
    Write-Error "Azure CLI ('az') was not found on PATH. Install it from https://learn.microsoft.com/cli/azure/install-azure-cli, then re-run."
    return
}

$extensions = az extension list --output json --only-show-errors 2>$null | ConvertFrom-Json
if (-not ($extensions | Where-Object { $_.name -eq 'azure-devops' })) {
    Write-Error "Azure CLI extension 'azure-devops' is not installed. Run: az extension add --name azure-devops"
    return
}

if ([string]::IsNullOrWhiteSpace($State) -and [string]::IsNullOrWhiteSpace($Comment)) {
    Write-Error "At least one of -State or -Comment is required."
    return
}

$currentRaw = az boards work-item show --id $WorkItemId --organization $Organization --output json --only-show-errors 2>$null
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($currentRaw)) {
    Write-Error "Work item $WorkItemId is not reachable in '$Organization' / '$Project'. No mutation performed."
    return
}

$current = $currentRaw | ConvertFrom-Json
$currentState = $current.fields.'System.State'

if (-not [string]::IsNullOrWhiteSpace($State) -and $State -eq $currentState) {
    Write-Error "Work item $WorkItemId is already in state '$State'."
    return
}

$targetDescription = if ($State) { "work item $WorkItemId -> $State" } else { "work item $WorkItemId (comment only)" }

if ($PSCmdlet.ShouldProcess($targetDescription, "Update Azure DevOps work item")) {
    $cliArgs = @('boards', 'work-item', 'update', '--id', $WorkItemId, '--organization', $Organization, '--output', 'json', '--only-show-errors')
    if (-not [string]::IsNullOrWhiteSpace($State)) { $cliArgs += @('--state', $State) }

    $discussionTempFile = $null
    if (-not [string]::IsNullOrWhiteSpace($Comment)) {
        # az.cmd re-parses the command line through cmd.exe on Windows: embedded newlines
        # truncate the value, shell metacharacters (< > & | ^) are misread as
        # redirection/pipe operators, and literal " breaks the argument boundary outright.
        # az CLI's generic "@file" syntax reads the value straight from disk instead, so the
        # raw text (including HTML tags) never touches the Windows command line at all.
        # AI disclaimer is mandatory on every posted comment (not just when the caller adds it).
        $discussionHtml = "$Comment`n`n<sub>Generated by AI (GitHub Copilot)</sub>"
        $discussionTempFile = [System.IO.Path]::Combine([System.IO.Path]::GetTempPath(), "aproda-ado-discussion-$([guid]::NewGuid()).txt")
        Set-Content -LiteralPath $discussionTempFile -Value $discussionHtml -NoNewline -Encoding utf8
        $cliArgs += @('--discussion', "@$discussionTempFile")
    }

    try {
        $updatedRaw = az @cliArgs 2>$null
    }
    finally {
        if ($discussionTempFile -and (Test-Path -LiteralPath $discussionTempFile)) {
            Remove-Item -LiteralPath $discussionTempFile -Force
        }
    }
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($updatedRaw)) {
        Write-Error "Failed to update work item $WorkItemId. No fallback performed."
        return
    }

    $updated = $updatedRaw | ConvertFrom-Json
    $orgUrl = $Organization.TrimEnd('/')
    $projectSegment = $Project -replace ' ', '%20'

    [ordered]@{
        updated = $true
        id      = $updated.id
        state   = $updated.fields.'System.State'
        url     = "$orgUrl/$projectSegment/_workitems/edit/$WorkItemId"
    } | ConvertTo-Json -Depth 5
}
